// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace MeAd.Raml
{
    [Route("quiz")]
    public partial class QuizController : Controller
    {


        /// <summary>
		/// Get top users from quiz - Top
		/// </summary>
        [HttpGet]
        [Route("top")]
        public virtual IActionResult GetBase()
        {
            // Do not modify this code
            return  ((IQuizController)this).Get();
        }

        /// <summary>
		/// Get a quiz with specific ID - QuizId
		/// </summary>
		/// <param name="quizID"></param>
        [HttpGet]
        [Route("{ID}")]
        public virtual IActionResult GetByQuizIDBase(string quizID)
        {
            // Do not modify this code
            return  ((IQuizController)this).GetByQuizID(quizID);
        }
    }
}
