// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace MeAd.Raml
{
    [Route("search")]
    public partial class SearchController : Controller
    {


        /// <summary>
		/// Search by country name - Country
		/// </summary>
		/// <param name="countryName"></param>
        [HttpGet]
        [Route("countries/{countryName}")]
        public virtual IActionResult GetBase(string countryName)
        {
            // Do not modify this code
            return  ((ISearchController)this).Get(countryName);
        }

        /// <summary>
		/// Search by disease name - Disease
		/// </summary>
		/// <param name="diseaseName"></param>
        [HttpGet]
        [Route("disease/{diseaseName}")]
        public virtual IActionResult GetDiseaseByDiseaseNameBase(string diseaseName)
        {
            // Do not modify this code
            return  ((ISearchController)this).GetDiseaseByDiseaseName(diseaseName);
        }
    }
}
