// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace MeAd.Raml
{
    [Route("users/{id}")]
    public partial class UsersIdController : Controller
    {


        /// <summary>
		/// View profile of an user - User
		/// </summary>
		/// <param name="id"></param>
        [HttpGet]
        [Route("")]
        public virtual IActionResult GetBase(string id)
        {
            // Do not modify this code
            return  ((IUsersIdController)this).Get(id);
        }

        /// <summary>
		/// The user can edit his profile - User
		/// </summary>
		/// <param name="content"></param>
		/// <param name="id"></param>
        [HttpPost]
        [Route("")]
        public virtual IActionResult PostBase([FromBody] string content,string id)
        {
            // Do not modify this code
            return  ((IUsersIdController)this).Post(content,id);
        }
    }
}
